import * as Graphql from'@arangodb/foxx/graphql';function g(a,b){if(!a)throw Error(b);}function k(a){return"object"==typeof a&&null!==a}function aa(a,b){if(!a)throw Error(null!=b?b:"Unexpected invariant triggered.");}let ba=/\r\n|[\n\r]/g;function ca(a,b){let c=0,d=1;for(let e of a.body.matchAll(ba)){"number"===typeof e.index||aa(!1);if(e.index>=b)break;c=e.index+e[0].length;d+=1}return{line:d,column:b+1-c}}
function da(a,b){var c=a.locationOffset.column-1,d="".padStart(c)+a.body,e=b.line-1;let h=b.line+(a.locationOffset.line-1);b=b.column+(1===b.line?c:0);a=`${a.name}:${h}:${b}\n`;c=d.split(/\r\n|[\n\r]/g);d=c[e];if(120<d.length){e=Math.floor(b/80);b%=80;c=[];for(let f=0;f<d.length;f+=80)c.push(d.slice(f,f+80));return a+ea([[`${h} |`,c[0]],...c.slice(1,e+1).map(f=>["|",f]),["|","^".padStart(b)],["|",c[e+1]]])}return a+ea([[`${h-1} |`,c[e-1]],[`${h} |`,d],["|","^".padStart(b)],[`${h+1} |`,c[e+1]]])}
function ea(a){a=a.filter(([,c])=>void 0!==c);let b=Math.max(...a.map(([c])=>c.length));return a.map(([c,d])=>c.padStart(b)+(d?" "+d:"")).join("\n")}function ia(a){let b=a[0];return null==b||"kind"in b||"length"in b?{nodes:b,source:a[1],positions:a[2],path:a[3],originalError:a[4],extensions:a[5]}:b}
class l extends Error{constructor(a,...b){var c,d,e;let {nodes:h,source:f,positions:y,path:w,originalError:v,extensions:z}=ia(b);super(a);this.name="GraphQLError";this.path=null!==w&&void 0!==w?w:void 0;this.originalError=null!==v&&void 0!==v?v:void 0;this.nodes=ja(Array.isArray(h)?h:h?[h]:void 0);a=ja(null===(c=this.nodes)||void 0===c?void 0:c.map(x=>x.loc).filter(x=>null!=x));this.source=null!==f&&void 0!==f?f:null===a||void 0===a?void 0:null===(d=a[0])||void 0===d?void 0:d.source;this.positions=
null!==y&&void 0!==y?y:null===a||void 0===a?void 0:a.map(x=>x.start);this.locations=y&&f?y.map(x=>ca(f,x)):null===a||void 0===a?void 0:a.map(x=>ca(x.source,x.start));c=k(null===v||void 0===v?void 0:v.extensions)?null===v||void 0===v?void 0:v.extensions:void 0;this.extensions=null!==(e=null!==z&&void 0!==z?z:c)&&void 0!==e?e:Object.create(null);Object.defineProperties(this,{message:{writable:!0,enumerable:!0},name:{enumerable:!1},nodes:{enumerable:!1},source:{enumerable:!1},positions:{enumerable:!1},
originalError:{enumerable:!1}});null!==v&&void 0!==v&&v.stack?Object.defineProperty(this,"stack",{value:v.stack,writable:!0,configurable:!0}):Error.captureStackTrace?Error.captureStackTrace(this,l):Object.defineProperty(this,"stack",{value:Error().stack,writable:!0,configurable:!0})}get [Symbol.toStringTag](){return"GraphQLError"}toString(){var a=this.message;if(this.nodes)for(let c of this.nodes){if(c.loc){var b=c.loc;b=da(b.source,ca(b.source,b.start));a+="\n\n"+b}}else if(this.source&&this.locations)for(b of this.locations)a+=
"\n\n"+da(this.source,b);return a}toJSON(){let a={message:this.message};null!=this.locations&&(a.locations=this.locations);null!=this.path&&(a.path=this.path);null!=this.extensions&&0<Object.keys(this.extensions).length&&(a.extensions=this.extensions);return a}}function ja(a){return void 0===a||0===a.length?void 0:a}
let ka={Name:[],Document:["definitions"],OperationDefinition:["name","variableDefinitions","directives","selectionSet"],VariableDefinition:["variable","type","defaultValue","directives"],Variable:["name"],SelectionSet:["selections"],Field:["alias","name","arguments","directives","selectionSet"],Argument:["name","value"],FragmentSpread:["name","directives"],InlineFragment:["typeCondition","directives","selectionSet"],FragmentDefinition:["name","variableDefinitions","typeCondition","directives","selectionSet"],
IntValue:[],FloatValue:[],StringValue:[],BooleanValue:[],NullValue:[],EnumValue:[],ListValue:["values"],ObjectValue:["fields"],ObjectField:["name","value"],Directive:["name","arguments"],NamedType:["name"],ListType:["type"],NonNullType:["type"],SchemaDefinition:["description","directives","operationTypes"],OperationTypeDefinition:["type"],ScalarTypeDefinition:["description","name","directives"],ObjectTypeDefinition:["description","name","interfaces","directives","fields"],FieldDefinition:["description",
"name","arguments","type","directives"],InputValueDefinition:["description","name","type","defaultValue","directives"],InterfaceTypeDefinition:["description","name","interfaces","directives","fields"],UnionTypeDefinition:["description","name","directives","types"],EnumTypeDefinition:["description","name","directives","values"],EnumValueDefinition:["description","name","directives"],InputObjectTypeDefinition:["description","name","directives","fields"],DirectiveDefinition:["description","name","arguments",
"locations"],SchemaExtension:["directives","operationTypes"],ScalarTypeExtension:["name","directives"],ObjectTypeExtension:["name","interfaces","directives","fields"],InterfaceTypeExtension:["name","interfaces","directives","fields"],UnionTypeExtension:["name","directives","types"],EnumTypeExtension:["name","directives","values"],InputObjectTypeExtension:["name","directives","fields"]},la=new Set(Object.keys(ka));
function ma(a){a=null===a||void 0===a?void 0:a.kind;return"string"===typeof a&&la.has(a)}let m;var na=m||(m={});na.QUERY="query";na.MUTATION="mutation";na.SUBSCRIPTION="subscription";let n;var p=n||(n={});p.QUERY="QUERY";p.MUTATION="MUTATION";p.SUBSCRIPTION="SUBSCRIPTION";p.FIELD="FIELD";p.FRAGMENT_DEFINITION="FRAGMENT_DEFINITION";p.FRAGMENT_SPREAD="FRAGMENT_SPREAD";p.INLINE_FRAGMENT="INLINE_FRAGMENT";p.VARIABLE_DEFINITION="VARIABLE_DEFINITION";p.SCHEMA="SCHEMA";p.SCALAR="SCALAR";p.OBJECT="OBJECT";
p.FIELD_DEFINITION="FIELD_DEFINITION";p.ARGUMENT_DEFINITION="ARGUMENT_DEFINITION";p.INTERFACE="INTERFACE";p.UNION="UNION";p.ENUM="ENUM";p.ENUM_VALUE="ENUM_VALUE";p.INPUT_OBJECT="INPUT_OBJECT";p.INPUT_FIELD_DEFINITION="INPUT_FIELD_DEFINITION";let q;var r=q||(q={});r.NAME="Name";r.DOCUMENT="Document";r.OPERATION_DEFINITION="OperationDefinition";r.VARIABLE_DEFINITION="VariableDefinition";r.SELECTION_SET="SelectionSet";r.FIELD="Field";r.ARGUMENT="Argument";r.FRAGMENT_SPREAD="FragmentSpread";
r.INLINE_FRAGMENT="InlineFragment";r.FRAGMENT_DEFINITION="FragmentDefinition";r.VARIABLE="Variable";r.INT="IntValue";r.FLOAT="FloatValue";r.STRING="StringValue";r.BOOLEAN="BooleanValue";r.NULL="NullValue";r.ENUM="EnumValue";r.LIST="ListValue";r.OBJECT="ObjectValue";r.OBJECT_FIELD="ObjectField";r.DIRECTIVE="Directive";r.NAMED_TYPE="NamedType";r.LIST_TYPE="ListType";r.NON_NULL_TYPE="NonNullType";r.SCHEMA_DEFINITION="SchemaDefinition";r.OPERATION_TYPE_DEFINITION="OperationTypeDefinition";
r.SCALAR_TYPE_DEFINITION="ScalarTypeDefinition";r.OBJECT_TYPE_DEFINITION="ObjectTypeDefinition";r.FIELD_DEFINITION="FieldDefinition";r.INPUT_VALUE_DEFINITION="InputValueDefinition";r.INTERFACE_TYPE_DEFINITION="InterfaceTypeDefinition";r.UNION_TYPE_DEFINITION="UnionTypeDefinition";r.ENUM_TYPE_DEFINITION="EnumTypeDefinition";r.ENUM_VALUE_DEFINITION="EnumValueDefinition";r.INPUT_OBJECT_TYPE_DEFINITION="InputObjectTypeDefinition";r.DIRECTIVE_DEFINITION="DirectiveDefinition";r.SCHEMA_EXTENSION="SchemaExtension";
r.SCALAR_TYPE_EXTENSION="ScalarTypeExtension";r.OBJECT_TYPE_EXTENSION="ObjectTypeExtension";r.INTERFACE_TYPE_EXTENSION="InterfaceTypeExtension";r.UNION_TYPE_EXTENSION="UnionTypeExtension";r.ENUM_TYPE_EXTENSION="EnumTypeExtension";r.INPUT_OBJECT_TYPE_EXTENSION="InputObjectTypeExtension";function oa(a){return 9===a||32===a}
function ta(a,b){let c=a.replace(/"""/g,'\\"""');var d=c.split(/\r\n|[\n\r]/g);let e=1===d.length;d=1<d.length&&d.slice(1).every(w=>0===w.length||oa(w.charCodeAt(0)));var h=c.endsWith('\\"""'),f=a.endsWith('"')&&!h;let y=a.endsWith("\\");f=f||y;b=!(null!==b&&void 0!==b&&b.minimize)&&(!e||70<a.length||f||d||h);h="";a=e&&oa(a.charCodeAt(0));if(b&&!a||d)h+="\n";h+=c;if(b||f)h+="\n";return'"""'+h+'"""'}function t(a){return ua(a,[])}
function ua(a,b){switch(typeof a){case "string":return JSON.stringify(a);case "function":return a.name?`[function ${a.name}]`:"[function]";case "object":return va(a,b);default:return String(a)}}
function va(a,b){if(null===a)return"null";if(b.includes(a))return"[Circular]";b=[...b,a];if("function"===typeof a.toJSON){var c=a.toJSON();if(c!==a)return"string"===typeof c?c:ua(c,b)}else if(Array.isArray(a)){if(0===a.length)a="[]";else if(2<b.length)a="[Array]";else{c=Math.min(10,a.length);var d=a.length-c,e=[];for(let h=0;h<c;++h)e.push(ua(a[h],b));1===d?e.push("... 1 more item"):1<d&&e.push(`... ${d} more items`);a="["+e.join(", ")+"]"}return a}return wa(a,b)}
function wa(a,b){let c=Object.entries(a);return 0===c.length?"{}":2<b.length?"["+xa(a)+"]":"{ "+c.map(([d,e])=>d+": "+ua(e,b)).join(", ")+" }"}function xa(a){let b=Object.prototype.toString.call(a).replace(/^\[object /,"").replace(/]$/,"");return"Object"===b&&"function"===typeof a.constructor&&(a=a.constructor.name,"string"===typeof a&&""!==a)?a:b}
let u="production"===process.env.NODE_ENV?function(a,b){return a instanceof b}:function(a,b){if(a instanceof b)return!0;if("object"===typeof a&&null!==a){var c;b=b.prototype[Symbol.toStringTag];const d=Symbol.toStringTag in a?a[Symbol.toStringTag]:null===(c=a.constructor)||void 0===c?void 0:c.name;if(b===d)throw a=t(a),Error(`Cannot use ${b} "${a}" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.`);}return!1};function ya(a,b){let [c,d]=b?[a,b]:[void 0,a];a=" Did you mean ";c&&(a+=c+" ");b=d.map(h=>`"${h}"`);switch(b.length){case 0:return"";case 1:return a+b[0]+"?";case 2:return a+b[0]+" or "+b[1]+"?"}b=b.slice(0,5);let e=b.pop();return a+b.join(", ")+", or "+e+"?"}function za(a){return a}function Aa(a,b){let c=Object.create(null);for(let d of a)c[b(d)]=d;return c}function Ba(a,b,c){let d=Object.create(null);for(let e of a)d[b(e)]=c(e);return d}
function Ca(a,b){let c=Object.create(null);for(let d of Object.keys(a))c[d]=b(a[d],d);return c}function Ea(a,b){let c=0,d=0;for(;c<a.length&&d<b.length;){var e=a.charCodeAt(c);let h=b.charCodeAt(d);if(Fa(e)&&Fa(h)){let f=0;do++c,f=10*f+e-48,e=a.charCodeAt(c);while(Fa(e)&&0<f);e=0;do++d,e=10*e+h-48,h=b.charCodeAt(d);while(Fa(h)&&0<e);if(f<e)return-1;if(f>e)return 1}else{if(e<h)return-1;if(e>h)return 1;++c;++d}}return a.length-b.length}function Fa(a){return!isNaN(a)&&48<=a&&57>=a}
function Ga(a,b){let c=Object.create(null),d=new Ha(a);a=Math.floor(.4*a.length)+1;for(let e of b)b=d.measure(e,a),void 0!==b&&(c[e]=b);return Object.keys(c).sort((e,h)=>{let f=c[e]-c[h];return 0!==f?f:Ea(e,h)})}
class Ha{constructor(a){this._input=a;this._inputLowerCase=a.toLowerCase();this._inputArray=Ia(this._inputLowerCase);this._rows=[Array(a.length+1).fill(0),Array(a.length+1).fill(0),Array(a.length+1).fill(0)]}measure(a,b){if(this._input===a)return 0;a=a.toLowerCase();if(this._inputLowerCase===a)return 1;a=Ia(a);let c=this._inputArray;if(a.length<c.length){var d=a;a=c;c=d}d=a.length;let e=c.length;if(!(d-e>b)){var h=this._rows;for(var f=0;f<=e;f++)h[0][f]=f;for(f=1;f<=d;f++){let y=h[(f-1)%3],w=h[f%
3],v=w[0]=f;for(let z=1;z<=e;z++){let x=Math.min(y[z]+1,w[z-1]+1,y[z-1]+(a[f-1]===c[z-1]?0:1));1<f&&1<z&&a[f-1]===c[z-2]&&a[f-2]===c[z-1]&&(x=Math.min(x,h[(f-2)%3][z-2]+1));x<v&&(v=x);w[z]=x}if(v>b)return}a=h[d%3][e];return a<=b?a:void 0}}}function Ia(a){let b=a.length,c=Array(b);for(let d=0;d<b;++d)c[d]=a.charCodeAt(d);return c}
function A(a){if(null==a)return Object.create(null);if(null===Object.getPrototypeOf(a))return a;let b=Object.create(null);for(let [c,d]of Object.entries(a))b[c]=d;return b}let Ja=/[\x00-\x1f\x22\x5c\x7f-\x9f]/g;function Ka(a){return La[a.charCodeAt(0)]}
let La='\\u0000 \\u0001 \\u0002 \\u0003 \\u0004 \\u0005 \\u0006 \\u0007 \\b \\t \\n \\u000B \\f \\r \\u000E \\u000F \\u0010 \\u0011 \\u0012 \\u0013 \\u0014 \\u0015 \\u0016 \\u0017 \\u0018 \\u0019 \\u001A \\u001B \\u001C \\u001D \\u001E \\u001F   \\"                                                          \\\\                                   \\u007F \\u0080 \\u0081 \\u0082 \\u0083 \\u0084 \\u0085 \\u0086 \\u0087 \\u0088 \\u0089 \\u008A \\u008B \\u008C \\u008D \\u008E \\u008F \\u0090 \\u0091 \\u0092 \\u0093 \\u0094 \\u0095 \\u0096 \\u0097 \\u0098 \\u0099 \\u009A \\u009B \\u009C \\u009D \\u009E \\u009F'.split(" "),Ma=
Object.freeze({});
function B(a,b,c=ka){let d=new Map;for(var e of Object.values(q)){var h=d,f=h.set,y=e;var w=b[e];w="object"===typeof w?w:"function"===typeof w?{enter:w,leave:void 0}:{enter:b.enter,leave:b.leave};f.call(h,y,w)}h=void 0;var v=Array.isArray(a);let z=[a],x=-1;var D=[];f=a;e=y=void 0;w=[];let fa=[];do{x++;let U=x===z.length,Da=U&&0!==D.length;if(U){y=0===fa.length?void 0:w[w.length-1];f=e;e=fa.pop();if(Da)if(v){f=f.slice();v=0;for(let [pa,ha]of D)D=pa-v,null===ha?(f.splice(D,1),v++):f[D]=ha}else{f=Object.defineProperties({},
Object.getOwnPropertyDescriptors(f));for(let [pa,ha]of D)f[pa]=ha}x=h.index;z=h.keys;D=h.edits;v=h.inArray;h=h.prev}else if(e){y=v?x:z[x];f=e[y];if(null===f||void 0===f)continue;w.push(y)}var G=void 0;if(!Array.isArray(f)){var qa,ra;ma(f)||g(!1,`Invalid AST Node: ${t(f)}.`);G=U?null===(qa=d.get(f.kind))||void 0===qa?void 0:qa.leave:null===(ra=d.get(f.kind))||void 0===ra?void 0:ra.enter;G=null===G||void 0===G?void 0:G.call(b,f,y,e,w,fa);if(G===Ma)break;if(!1===G){if(!U){w.pop();continue}}else if(void 0!==
G&&(D.push([y,G]),!U))if(ma(G))f=G;else{w.pop();continue}}void 0===G&&Da&&D.push([y,f]);if(U)w.pop();else{var sa;h={inArray:v,index:x,keys:z,edits:D,prev:h};z=(v=Array.isArray(f))?f:null!==(sa=c[f.kind])&&void 0!==sa?sa:[];x=-1;D=[];e&&fa.push(e);e=f}}while(void 0!==h);return 0!==D.length?D[D.length-1][1]:a}
let H={Name:{leave:a=>a.value},Variable:{leave:a=>"$"+a.name},Document:{leave:a=>C(a.definitions,"\n\n")},OperationDefinition:{leave(a){var b=E("(",C(a.variableDefinitions,", "),")");b=C([a.operation,C([a.name,b]),C(a.directives," ")]," ");return("query"===b?"":b+" ")+a.selectionSet}},VariableDefinition:{leave:({variable:a,type:b,defaultValue:c,directives:d})=>a+": "+b+E(" = ",c)+E(" ",C(d," "))},SelectionSet:{leave:({selections:a})=>F(a)},Field:{leave({alias:a,name:b,arguments:c,directives:d,selectionSet:e}){a=
E("",a,": ")+b;b=a+E("(",C(c,", "),")");80<b.length&&(b=a+E("(\n",Na(C(c,"\n")),"\n)"));return C([b,C(d," "),e]," ")}},Argument:{leave:({name:a,value:b})=>a+": "+b},FragmentSpread:{leave:({name:a,directives:b})=>"..."+a+E(" ",C(b," "))},InlineFragment:{leave:({typeCondition:a,directives:b,selectionSet:c})=>C(["...",E("on ",a),C(b," "),c]," ")},FragmentDefinition:{leave:({name:a,typeCondition:b,variableDefinitions:c,directives:d,selectionSet:e})=>`fragment ${a}${E("(",C(c,", "),")")} `+`on ${b} ${E("",
C(d," ")," ")}`+e},IntValue:{leave:({value:a})=>a},FloatValue:{leave:({value:a})=>a},StringValue:{leave:({value:a,block:b})=>b?ta(a):`"${a.replace(Ja,Ka)}"`},BooleanValue:{leave:({value:a})=>a?"true":"false"},NullValue:{leave:()=>"null"},EnumValue:{leave:({value:a})=>a},ListValue:{leave:({values:a})=>"["+C(a,", ")+"]"},ObjectValue:{leave:({fields:a})=>"{"+C(a,", ")+"}"},ObjectField:{leave:({name:a,value:b})=>a+": "+b},Directive:{leave:({name:a,arguments:b})=>"@"+a+E("(",C(b,", "),")")},NamedType:{leave:({name:a})=>
a},ListType:{leave:({type:a})=>"["+a+"]"},NonNullType:{leave:({type:a})=>a+"!"},SchemaDefinition:{leave:({description:a,directives:b,operationTypes:c})=>E("",a,"\n")+C(["schema",C(b," "),F(c)]," ")},OperationTypeDefinition:{leave:({operation:a,type:b})=>a+": "+b},ScalarTypeDefinition:{leave:({description:a,name:b,directives:c})=>E("",a,"\n")+C(["scalar",b,C(c," ")]," ")},ObjectTypeDefinition:{leave:({description:a,name:b,interfaces:c,directives:d,fields:e})=>E("",a,"\n")+C(["type",b,E("implements ",
C(c," & ")),C(d," "),F(e)]," ")},FieldDefinition:{leave:({description:a,name:b,arguments:c,type:d,directives:e})=>E("",a,"\n")+b+(Oa(c)?E("(\n",Na(C(c,"\n")),"\n)"):E("(",C(c,", "),")"))+": "+d+E(" ",C(e," "))},InputValueDefinition:{leave:({description:a,name:b,type:c,defaultValue:d,directives:e})=>E("",a,"\n")+C([b+": "+c,E("= ",d),C(e," ")]," ")},InterfaceTypeDefinition:{leave:({description:a,name:b,interfaces:c,directives:d,fields:e})=>E("",a,"\n")+C(["interface",b,E("implements ",C(c," & ")),
C(d," "),F(e)]," ")},UnionTypeDefinition:{leave:({description:a,name:b,directives:c,types:d})=>E("",a,"\n")+C(["union",b,C(c," "),E("= ",C(d," | "))]," ")},EnumTypeDefinition:{leave:({description:a,name:b,directives:c,values:d})=>E("",a,"\n")+C(["enum",b,C(c," "),F(d)]," ")},EnumValueDefinition:{leave:({description:a,name:b,directives:c})=>E("",a,"\n")+C([b,C(c," ")]," ")},InputObjectTypeDefinition:{leave:({description:a,name:b,directives:c,fields:d})=>E("",a,"\n")+C(["input",b,C(c," "),F(d)]," ")},
DirectiveDefinition:{leave:({description:a,name:b,arguments:c,repeatable:d,locations:e})=>E("",a,"\n")+"directive @"+b+(Oa(c)?E("(\n",Na(C(c,"\n")),"\n)"):E("(",C(c,", "),")"))+(d?" repeatable":"")+" on "+C(e," | ")},SchemaExtension:{leave:({directives:a,operationTypes:b})=>C(["extend schema",C(a," "),F(b)]," ")},ScalarTypeExtension:{leave:({name:a,directives:b})=>C(["extend scalar",a,C(b," ")]," ")},ObjectTypeExtension:{leave:({name:a,interfaces:b,directives:c,fields:d})=>C(["extend type",a,E("implements ",
C(b," & ")),C(c," "),F(d)]," ")},InterfaceTypeExtension:{leave:({name:a,interfaces:b,directives:c,fields:d})=>C(["extend interface",a,E("implements ",C(b," & ")),C(c," "),F(d)]," ")},UnionTypeExtension:{leave:({name:a,directives:b,types:c})=>C(["extend union",a,C(b," "),E("= ",C(c," | "))]," ")},EnumTypeExtension:{leave:({name:a,directives:b,values:c})=>C(["extend enum",a,C(b," "),F(c)]," ")},InputObjectTypeExtension:{leave:({name:a,directives:b,fields:c})=>C(["extend input",a,C(b," "),F(c)]," ")}};
function C(a,b=""){var c;return null!==(c=null===a||void 0===a?void 0:a.filter(d=>d).join(b))&&void 0!==c?c:""}function F(a){return E("{\n",Na(C(a,"\n")),"\n}")}function E(a,b,c=""){return null!=b&&""!==b?a+b+c:""}function Na(a){return E("  ",a.replace(/\n/g,"\n  "))}function Oa(a){var b;return null!==(b=null===a||void 0===a?void 0:a.some(c=>c.includes("\n")))&&void 0!==b?b:!1}
function Pa(a,b){switch(a.kind){case q.NULL:return null;case q.INT:return parseInt(a.value,10);case q.FLOAT:return parseFloat(a.value);case q.STRING:case q.ENUM:case q.BOOLEAN:return a.value;case q.LIST:return a.values.map(c=>Pa(c,b));case q.OBJECT:return Ba(a.fields,c=>c.name.value,c=>Pa(c.value,b));case q.VARIABLE:return null===b||void 0===b?void 0:b[a.name.value]}}
function I(a){null!=a||g(!1,"Must provide name.");"string"===typeof a||g(!1,"Expected name to be a string.");if(0===a.length)throw new l("Expected name to be a non-empty string.");for(let c=1;c<a.length;++c){var b=a.charCodeAt(c);if(!(97<=b&&122>=b||65<=b&&90>=b||48<=b&&57>=b||95===b))throw new l(`Names must only contain [_a-zA-Z0-9] but "${a}" does not.`);}b=a.charCodeAt(0);if(!(97<=b&&122>=b||65<=b&&90>=b||95===b))throw new l(`Names must start with [_a-zA-Z] but "${a}" does not.`);return a}
function Qa(a){return u(a,J)||u(a,K)||u(a,L)||u(a,M)||u(a,N)||u(a,O)||u(a,P)||u(a,Q)}class P{constructor(a){Qa(a)||g(!1,`Expected ${t(a)} to be a GraphQL type.`);this.ofType=a}get [Symbol.toStringTag](){return"GraphQLList"}toString(){return"["+String(this.ofType)+"]"}toJSON(){return this.toString()}}
class Q{constructor(a){Qa(a)&&!u(a,Q)||g(!1,`Expected ${t(a)} to be a GraphQL nullable type.`);this.ofType=a}get [Symbol.toStringTag](){return"GraphQLNonNull"}toString(){return String(this.ofType)+"!"}toJSON(){return this.toString()}}function Ra(a){return u(a,P)||u(a,Q)}function Sa(a){return"function"===typeof a?a():a}function Ta(a){return"function"===typeof a?a():a}
class J{constructor(a){var b,c,d,e;let h=null!==(b=a.parseValue)&&void 0!==b?b:za;this.name=I(a.name);this.description=a.description;this.specifiedByURL=a.specifiedByURL;this.serialize=null!==(c=a.serialize)&&void 0!==c?c:za;this.parseValue=h;this.parseLiteral=null!==(d=a.parseLiteral)&&void 0!==d?d:(f,y)=>h(Pa(f,y));this.extensions=A(a.extensions);this.astNode=a.astNode;this.extensionASTNodes=null!==(e=a.extensionASTNodes)&&void 0!==e?e:[];null==a.specifiedByURL||"string"===typeof a.specifiedByURL||
g(!1,`${this.name} must provide "specifiedByURL" as a string, `+`but got: ${t(a.specifiedByURL)}.`);null==a.serialize||"function"===typeof a.serialize||g(!1,`${this.name} must provide "serialize" function. If this custom Scalar is also used as an input type, ensure "parseValue" and "parseLiteral" functions are also provided.`);a.parseLiteral&&("function"===typeof a.parseValue&&"function"===typeof a.parseLiteral||g(!1,`${this.name} must provide both "parseValue" and "parseLiteral" functions.`))}get [Symbol.toStringTag](){return"GraphQLScalarType"}toConfig(){return{name:this.name,
description:this.description,specifiedByURL:this.specifiedByURL,serialize:this.serialize,parseValue:this.parseValue,parseLiteral:this.parseLiteral,extensions:this.extensions,astNode:this.astNode,extensionASTNodes:this.extensionASTNodes}}toString(){return this.name}toJSON(){return this.toString()}}
class K{constructor(a){var b;this.name=I(a.name);this.description=a.description;this.isTypeOf=a.isTypeOf;this.extensions=A(a.extensions);this.astNode=a.astNode;this.extensionASTNodes=null!==(b=a.extensionASTNodes)&&void 0!==b?b:[];this._fields=()=>Ua(a);this._interfaces=()=>Va(a);null==a.isTypeOf||"function"===typeof a.isTypeOf||g(!1,`${this.name} must provide "isTypeOf" as a function, `+`but got: ${t(a.isTypeOf)}.`)}get [Symbol.toStringTag](){return"GraphQLObjectType"}getFields(){"function"===typeof this._fields&&
(this._fields=this._fields());return this._fields}getInterfaces(){"function"===typeof this._interfaces&&(this._interfaces=this._interfaces());return this._interfaces}toConfig(){return{name:this.name,description:this.description,interfaces:this.getInterfaces(),fields:Wa(this.getFields()),isTypeOf:this.isTypeOf,extensions:this.extensions,astNode:this.astNode,extensionASTNodes:this.extensionASTNodes}}toString(){return this.name}toJSON(){return this.toString()}}
function Va(a){var b;let c=Sa(null!==(b=a.interfaces)&&void 0!==b?b:[]);Array.isArray(c)||g(!1,`${a.name} interfaces must be an Array or a function which returns an Array.`);return c}
function Ua(a){let b=Ta(a.fields);R(b)||g(!1,`${a.name} fields must be an object with field names as keys or a function which returns such an object.`);return Ca(b,(c,d)=>{var e;R(c)||g(!1,`${a.name}.${d} field config must be an object.`);null==c.resolve||"function"===typeof c.resolve||g(!1,`${a.name}.${d} field resolver must be a function if `+`provided, but got: ${t(c.resolve)}.`);let h=null!==(e=c.args)&&void 0!==e?e:{};R(h)||g(!1,`${a.name}.${d} args must be an object with argument names as keys.`);
return{name:I(d),description:c.description,type:c.type,args:Xa(h),resolve:c.resolve,subscribe:c.subscribe,deprecationReason:c.deprecationReason,extensions:A(c.extensions),astNode:c.astNode}})}function Xa(a){return Object.entries(a).map(([b,c])=>({name:I(b),description:c.description,type:c.type,defaultValue:c.defaultValue,deprecationReason:c.deprecationReason,extensions:A(c.extensions),astNode:c.astNode}))}function R(a){return k(a)&&!Array.isArray(a)}
function Wa(a){return Ca(a,b=>({description:b.description,type:b.type,args:Ya(b.args),resolve:b.resolve,subscribe:b.subscribe,deprecationReason:b.deprecationReason,extensions:b.extensions,astNode:b.astNode}))}function Ya(a){return Ba(a,b=>b.name,b=>({description:b.description,type:b.type,defaultValue:b.defaultValue,deprecationReason:b.deprecationReason,extensions:b.extensions,astNode:b.astNode}))}
class L{constructor(a){var b;this.name=I(a.name);this.description=a.description;this.resolveType=a.resolveType;this.extensions=A(a.extensions);this.astNode=a.astNode;this.extensionASTNodes=null!==(b=a.extensionASTNodes)&&void 0!==b?b:[];this._fields=Ua.bind(void 0,a);this._interfaces=Va.bind(void 0,a);null==a.resolveType||"function"===typeof a.resolveType||g(!1,`${this.name} must provide "resolveType" as a function, `+`but got: ${t(a.resolveType)}.`)}get [Symbol.toStringTag](){return"GraphQLInterfaceType"}getFields(){"function"===
typeof this._fields&&(this._fields=this._fields());return this._fields}getInterfaces(){"function"===typeof this._interfaces&&(this._interfaces=this._interfaces());return this._interfaces}toConfig(){return{name:this.name,description:this.description,interfaces:this.getInterfaces(),fields:Wa(this.getFields()),resolveType:this.resolveType,extensions:this.extensions,astNode:this.astNode,extensionASTNodes:this.extensionASTNodes}}toString(){return this.name}toJSON(){return this.toString()}}
class M{constructor(a){var b;this.name=I(a.name);this.description=a.description;this.resolveType=a.resolveType;this.extensions=A(a.extensions);this.astNode=a.astNode;this.extensionASTNodes=null!==(b=a.extensionASTNodes)&&void 0!==b?b:[];this._types=Za.bind(void 0,a);null==a.resolveType||"function"===typeof a.resolveType||g(!1,`${this.name} must provide "resolveType" as a function, `+`but got: ${t(a.resolveType)}.`)}get [Symbol.toStringTag](){return"GraphQLUnionType"}getTypes(){"function"===typeof this._types&&
(this._types=this._types());return this._types}toConfig(){return{name:this.name,description:this.description,types:this.getTypes(),resolveType:this.resolveType,extensions:this.extensions,astNode:this.astNode,extensionASTNodes:this.extensionASTNodes}}toString(){return this.name}toJSON(){return this.toString()}}function Za(a){let b=Sa(a.types);Array.isArray(b)||g(!1,`Must provide Array of types or a function which returns such an array for Union ${a.name}.`);return b}
class N{constructor(a){var b;this.name=I(a.name);this.description=a.description;this.extensions=A(a.extensions);this.astNode=a.astNode;this.extensionASTNodes=null!==(b=a.extensionASTNodes)&&void 0!==b?b:[];this._values=$a(this.name,a.values);this._valueLookup=new Map(this._values.map(c=>[c.value,c]));this._nameLookup=Aa(this._values,c=>c.name)}get [Symbol.toStringTag](){return"GraphQLEnumType"}getValues(){return this._values}getValue(a){return this._nameLookup[a]}serialize(a){let b=this._valueLookup.get(a);
if(void 0===b)throw new l(`Enum "${this.name}" cannot represent value: ${t(a)}`);return b.name}parseValue(a){if("string"!==typeof a)throw a=t(a),new l(`Enum "${this.name}" cannot represent non-string value: ${a}.`+ab(this,a));let b=this.getValue(a);if(null==b)throw new l(`Value "${a}" does not exist in "${this.name}" enum.`+ab(this,a));return b.value}parseLiteral(a){if(a.kind!==q.ENUM){var b=B(a,H);throw new l(`Enum "${this.name}" cannot represent non-enum value: ${b}.`+ab(this,b),a);}b=this.getValue(a.value);
if(null==b)throw b=B(a,H),new l(`Value "${b}" does not exist in "${this.name}" enum.`+ab(this,b),a);return b.value}toConfig(){let a=Ba(this.getValues(),b=>b.name,b=>({description:b.description,value:b.value,deprecationReason:b.deprecationReason,extensions:b.extensions,astNode:b.astNode}));return{name:this.name,description:this.description,values:a,extensions:this.extensions,astNode:this.astNode,extensionASTNodes:this.extensionASTNodes}}toString(){return this.name}toJSON(){return this.toString()}}
function ab(a,b){a=a.getValues().map(c=>c.name);b=Ga(b,a);return ya("the enum value",b)}
function $a(a,b){R(b)||g(!1,`${a} values must be an object with value names as keys.`);return Object.entries(b).map(([c,d])=>{R(d)||g(!1,`${a}.${c} must refer to an object with a "value" key `+`representing an internal value but got: ${t(d)}.`);if("true"===c||"false"===c||"null"===c)throw new l(`Enum values cannot be named: ${c}`);return{name:I(c),description:d.description,value:void 0!==d.value?d.value:c,deprecationReason:d.deprecationReason,extensions:A(d.extensions),astNode:d.astNode}})}
class O{constructor(a){var b;this.name=I(a.name);this.description=a.description;this.extensions=A(a.extensions);this.astNode=a.astNode;this.extensionASTNodes=null!==(b=a.extensionASTNodes)&&void 0!==b?b:[];this._fields=bb.bind(void 0,a)}get [Symbol.toStringTag](){return"GraphQLInputObjectType"}getFields(){"function"===typeof this._fields&&(this._fields=this._fields());return this._fields}toConfig(){let a=Ca(this.getFields(),b=>({description:b.description,type:b.type,defaultValue:b.defaultValue,deprecationReason:b.deprecationReason,
extensions:b.extensions,astNode:b.astNode}));return{name:this.name,description:this.description,fields:a,extensions:this.extensions,astNode:this.astNode,extensionASTNodes:this.extensionASTNodes}}toString(){return this.name}toJSON(){return this.toString()}}
function bb(a){let b=Ta(a.fields);R(b)||g(!1,`${a.name} fields must be an object with field names as keys or a function which returns such an object.`);return Ca(b,(c,d)=>{"resolve"in c&&g(!1,`${a.name}.${d} field has a resolve property, but Input Types cannot define resolvers.`);return{name:I(d),description:c.description,type:c.type,defaultValue:c.defaultValue,deprecationReason:c.deprecationReason,extensions:A(c.extensions),astNode:c.astNode}})}
let cb=new J({name:"Int",description:"The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.",serialize(a){a=S(a);if("boolean"===typeof a)return a?1:0;let b=a;"string"===typeof a&&""!==a&&(b=Number(a));if("number"!==typeof b||!Number.isInteger(b))throw new l(`Int cannot represent non-integer value: ${t(a)}`);if(2147483647<b||-2147483648>b)throw new l("Int cannot represent non 32-bit signed integer value: "+t(a));return b},
parseValue(a){if("number"!==typeof a||!Number.isInteger(a))throw new l(`Int cannot represent non-integer value: ${t(a)}`);if(2147483647<a||-2147483648>a)throw new l(`Int cannot represent non 32-bit signed integer value: ${a}`);return a},parseLiteral(a){if(a.kind!==q.INT)throw new l(`Int cannot represent non-integer value: ${B(a,H)}`,a);const b=parseInt(a.value,10);if(2147483647<b||-2147483648>b)throw new l(`Int cannot represent non 32-bit signed integer value: ${a.value}`,a);return b}}),db=new J({name:"Float",
description:"The `Float` scalar type represents signed double-precision fractional values as specified by [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point).",serialize(a){a=S(a);if("boolean"===typeof a)return a?1:0;let b=a;"string"===typeof a&&""!==a&&(b=Number(a));if("number"!==typeof b||!Number.isFinite(b))throw new l(`Float cannot represent non numeric value: ${t(a)}`);return b},parseValue(a){if("number"!==typeof a||!Number.isFinite(a))throw new l(`Float cannot represent non numeric value: ${t(a)}`);
return a},parseLiteral(a){if(a.kind!==q.FLOAT&&a.kind!==q.INT)throw new l(`Float cannot represent non numeric value: ${B(a,H)}`,a);return parseFloat(a.value)}}),T=new J({name:"String",description:"The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.",serialize(a){const b=S(a);if("string"===typeof b)return b;if("boolean"===typeof b)return b?"true":"false";if("number"===typeof b&&
Number.isFinite(b))return b.toString();throw new l(`String cannot represent value: ${t(a)}`);},parseValue(a){if("string"!==typeof a)throw new l(`String cannot represent a non string value: ${t(a)}`);return a},parseLiteral(a){if(a.kind!==q.STRING)throw new l(`String cannot represent a non string value: ${B(a,H)}`,a);return a.value}}),V=new J({name:"Boolean",description:"The `Boolean` scalar type represents `true` or `false`.",serialize(a){a=S(a);if("boolean"===typeof a)return a;if(Number.isFinite(a))return 0!==
a;throw new l(`Boolean cannot represent a non boolean value: ${t(a)}`);},parseValue(a){if("boolean"!==typeof a)throw new l(`Boolean cannot represent a non boolean value: ${t(a)}`);return a},parseLiteral(a){if(a.kind!==q.BOOLEAN)throw new l(`Boolean cannot represent a non boolean value: ${B(a,H)}`,a);return a.value}}),eb=new J({name:"ID",description:'The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.',
serialize(a){const b=S(a);if("string"===typeof b)return b;if(Number.isInteger(b))return String(b);throw new l(`ID cannot represent value: ${t(a)}`);},parseValue(a){if("string"===typeof a)return a;if("number"===typeof a&&Number.isInteger(a))return a.toString();throw new l(`ID cannot represent value: ${t(a)}`);},parseLiteral(a){if(a.kind!==q.STRING&&a.kind!==q.INT)throw new l("ID cannot represent a non-string and non-integer value: "+B(a,H),a);return a.value}});Object.freeze([T,cb,db,V,eb]);
function S(a){if(k(a)){if("function"===typeof a.valueOf){let b=a.valueOf();if(!k(b))return b}if("function"===typeof a.toJSON)return a.toJSON()}return a}
class fb{constructor(a){var b,c;this.name=I(a.name);this.description=a.description;this.locations=a.locations;this.isRepeatable=null!==(b=a.isRepeatable)&&void 0!==b?b:!1;this.extensions=A(a.extensions);this.astNode=a.astNode;Array.isArray(a.locations)||g(!1,`@${a.name} locations must be an Array.`);b=null!==(c=a.args)&&void 0!==c?c:{};k(b)&&!Array.isArray(b)||g(!1,`@${a.name} args must be an object with argument names as keys.`);this.args=Xa(b)}get [Symbol.toStringTag](){return"GraphQLDirective"}toConfig(){return{name:this.name,
description:this.description,locations:this.locations,args:Ya(this.args),isRepeatable:this.isRepeatable,extensions:this.extensions,astNode:this.astNode}}toString(){return"@"+this.name}toJSON(){return this.toString()}}
let gb=new fb({name:"include",description:"Directs the executor to include this field or fragment only when the `if` argument is true.",locations:[n.FIELD,n.FRAGMENT_SPREAD,n.INLINE_FRAGMENT],args:{if:{type:new Q(V),description:"Included when true."}}}),hb=new fb({name:"skip",description:"Directs the executor to skip this field or fragment when the `if` argument is true.",locations:[n.FIELD,n.FRAGMENT_SPREAD,n.INLINE_FRAGMENT],args:{if:{type:new Q(V),description:"Skipped when true."}}}),ib=new fb({name:"deprecated",
description:"Marks an element of a GraphQL schema as no longer supported.",locations:[n.FIELD_DEFINITION,n.ARGUMENT_DEFINITION,n.INPUT_FIELD_DEFINITION,n.ENUM_VALUE],args:{reason:{type:T,description:"Explains why this element was deprecated, usually also including a suggestion for how to access supported similar data. Formatted using the Markdown syntax, as specified by [CommonMark](https://commonmark.org/).",defaultValue:"No longer supported"}}}),jb=new fb({name:"specifiedBy",description:"Exposes a URL that specifies the behavior of this scalar.",
locations:[n.SCALAR],args:{url:{type:new Q(T),description:"The URL that specifies the behavior of this scalar."}}}),kb=Object.freeze([gb,hb,ib,jb]);
function lb(a,b){if(u(b,Q))return a=lb(a,b.ofType),(null===a||void 0===a?void 0:a.kind)===q.NULL?null:a;if(null===a)return{kind:q.NULL};if(void 0===a)return null;if(u(b,P)){b=b.ofType;if("object"===typeof a&&"function"===typeof(null===a||void 0===a?void 0:a[Symbol.iterator])){var c=[];for(var d of a)a=lb(d,b),null!=a&&c.push(a);return{kind:q.LIST,values:c}}return lb(a,b)}if(u(b,O)){if(!k(a))return null;d=[];for(c of Object.values(b.getFields()))(b=lb(a[c.name],c.type))&&d.push({kind:q.OBJECT_FIELD,
name:{kind:q.NAME,value:c.name},value:b});return{kind:q.OBJECT,fields:d}}if(u(b,J)||u(b,N)){a=b.serialize(a);if(null==a)return null;if("boolean"===typeof a)return{kind:q.BOOLEAN,value:a};if("number"===typeof a&&Number.isFinite(a))return a=String(a),mb.test(a)?{kind:q.INT,value:a}:{kind:q.FLOAT,value:a};if("string"===typeof a)return u(b,N)?{kind:q.ENUM,value:a}:b===eb&&mb.test(a)?{kind:q.INT,value:a}:{kind:q.STRING,value:a};throw new TypeError(`Cannot convert value to AST: ${t(a)}.`);}aa(!1,"Unexpected input type: "+
t(b))}
let mb=/^-?(?:0|[1-9][0-9]*)$/,ob=new K({name:"__Schema",description:"A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.",fields:()=>({description:{type:T,resolve:a=>a.description},types:{description:"A list of all types supported by this server.",type:new Q(new P(new Q(W))),resolve(a){return Object.values(a.getTypeMap())}},queryType:{description:"The type that query operations will be rooted at.",type:new Q(W),
resolve:a=>a.getQueryType()},mutationType:{description:"If this server supports mutation, the type that mutation operations will be rooted at.",type:W,resolve:a=>a.getMutationType()},subscriptionType:{description:"If this server support subscription, the type that subscription operations will be rooted at.",type:W,resolve:a=>a.getSubscriptionType()},directives:{description:"A list of all directives supported by this server.",type:new Q(new P(new Q(nb))),resolve:a=>a.getDirectives()}})}),nb=new K({name:"__Directive",
description:"A Directive provides a way to describe alternate runtime execution and type validation behavior in a GraphQL document.\n\nIn some cases, you need to provide options to alter GraphQL's execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.",fields:()=>({name:{type:new Q(T),resolve:a=>a.name},description:{type:T,resolve:a=>a.description},isRepeatable:{type:new Q(V),
resolve:a=>a.isRepeatable},locations:{type:new Q(new P(new Q(pb))),resolve:a=>a.locations},args:{type:new Q(new P(new Q(qb))),args:{includeDeprecated:{type:V,defaultValue:!1}},resolve(a,{includeDeprecated:b}){return b?a.args:a.args.filter(c=>null==c.deprecationReason)}}})}),pb=new N({name:"__DirectiveLocation",description:"A Directive can be adjacent to many parts of the GraphQL language, a __DirectiveLocation describes one such possible adjacencies.",values:{QUERY:{value:n.QUERY,description:"Location adjacent to a query operation."},
MUTATION:{value:n.MUTATION,description:"Location adjacent to a mutation operation."},SUBSCRIPTION:{value:n.SUBSCRIPTION,description:"Location adjacent to a subscription operation."},FIELD:{value:n.FIELD,description:"Location adjacent to a field."},FRAGMENT_DEFINITION:{value:n.FRAGMENT_DEFINITION,description:"Location adjacent to a fragment definition."},FRAGMENT_SPREAD:{value:n.FRAGMENT_SPREAD,description:"Location adjacent to a fragment spread."},INLINE_FRAGMENT:{value:n.INLINE_FRAGMENT,description:"Location adjacent to an inline fragment."},
VARIABLE_DEFINITION:{value:n.VARIABLE_DEFINITION,description:"Location adjacent to a variable definition."},SCHEMA:{value:n.SCHEMA,description:"Location adjacent to a schema definition."},SCALAR:{value:n.SCALAR,description:"Location adjacent to a scalar definition."},OBJECT:{value:n.OBJECT,description:"Location adjacent to an object type definition."},FIELD_DEFINITION:{value:n.FIELD_DEFINITION,description:"Location adjacent to a field definition."},ARGUMENT_DEFINITION:{value:n.ARGUMENT_DEFINITION,
description:"Location adjacent to an argument definition."},INTERFACE:{value:n.INTERFACE,description:"Location adjacent to an interface definition."},UNION:{value:n.UNION,description:"Location adjacent to a union definition."},ENUM:{value:n.ENUM,description:"Location adjacent to an enum definition."},ENUM_VALUE:{value:n.ENUM_VALUE,description:"Location adjacent to an enum value definition."},INPUT_OBJECT:{value:n.INPUT_OBJECT,description:"Location adjacent to an input object type definition."},INPUT_FIELD_DEFINITION:{value:n.INPUT_FIELD_DEFINITION,
description:"Location adjacent to an input object field definition."}}}),W=new K({name:"__Type",description:"The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.\n\nDepending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name, description and optional `specifiedByURL`, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types.",
fields:()=>({kind:{type:new Q(rb),resolve(a){if(u(a,J))return X.SCALAR;if(u(a,K))return X.OBJECT;if(u(a,L))return X.INTERFACE;if(u(a,M))return X.UNION;if(u(a,N))return X.ENUM;if(u(a,O))return X.INPUT_OBJECT;if(u(a,P))return X.LIST;if(u(a,Q))return X.NON_NULL;aa(!1,`Unexpected type: "${t(a)}".`)}},name:{type:T,resolve:a=>"name"in a?a.name:void 0},description:{type:T,resolve:a=>"description"in a?a.description:void 0},specifiedByURL:{type:T,resolve:a=>"specifiedByURL"in a?a.specifiedByURL:void 0},fields:{type:new P(new Q(sb)),
args:{includeDeprecated:{type:V,defaultValue:!1}},resolve(a,{includeDeprecated:b}){if(u(a,K)||u(a,L))return a=Object.values(a.getFields()),b?a:a.filter(c=>null==c.deprecationReason)}},interfaces:{type:new P(new Q(W)),resolve(a){if(u(a,K)||u(a,L))return a.getInterfaces()}},possibleTypes:{type:new P(new Q(W)),resolve(a,b,c,{schema:d}){if(u(a,L)||u(a,M))return d.getPossibleTypes(a)}},enumValues:{type:new P(new Q(tb)),args:{includeDeprecated:{type:V,defaultValue:!1}},resolve(a,{includeDeprecated:b}){if(u(a,
N))return a=a.getValues(),b?a:a.filter(c=>null==c.deprecationReason)}},inputFields:{type:new P(new Q(qb)),args:{includeDeprecated:{type:V,defaultValue:!1}},resolve(a,{includeDeprecated:b}){if(u(a,O))return a=Object.values(a.getFields()),b?a:a.filter(c=>null==c.deprecationReason)}},ofType:{type:W,resolve:a=>"ofType"in a?a.ofType:void 0}})}),sb=new K({name:"__Field",description:"Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type.",
fields:()=>({name:{type:new Q(T),resolve:a=>a.name},description:{type:T,resolve:a=>a.description},args:{type:new Q(new P(new Q(qb))),args:{includeDeprecated:{type:V,defaultValue:!1}},resolve(a,{includeDeprecated:b}){return b?a.args:a.args.filter(c=>null==c.deprecationReason)}},type:{type:new Q(W),resolve:a=>a.type},isDeprecated:{type:new Q(V),resolve:a=>null!=a.deprecationReason},deprecationReason:{type:T,resolve:a=>a.deprecationReason}})}),qb=new K({name:"__InputValue",description:"Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.",
fields:()=>({name:{type:new Q(T),resolve:a=>a.name},description:{type:T,resolve:a=>a.description},type:{type:new Q(W),resolve:a=>a.type},defaultValue:{type:T,description:"A GraphQL-formatted string representing the default value for this input value.",resolve(a){const {type:b,defaultValue:c}=a;return(a=lb(c,b))?B(a,H):null}},isDeprecated:{type:new Q(V),resolve:a=>null!=a.deprecationReason},deprecationReason:{type:T,resolve:a=>a.deprecationReason}})}),tb=new K({name:"__EnumValue",description:"One possible value for a given Enum. Enum values are unique values, not a placeholder for a string or numeric value. However an Enum value is returned in a JSON response as a string.",
fields:()=>({name:{type:new Q(T),resolve:a=>a.name},description:{type:T,resolve:a=>a.description},isDeprecated:{type:new Q(V),resolve:a=>null!=a.deprecationReason},deprecationReason:{type:T,resolve:a=>a.deprecationReason}})}),X;var Y=X||(X={});Y.SCALAR="SCALAR";Y.OBJECT="OBJECT";Y.INTERFACE="INTERFACE";Y.UNION="UNION";Y.ENUM="ENUM";Y.INPUT_OBJECT="INPUT_OBJECT";Y.LIST="LIST";Y.NON_NULL="NON_NULL";
let rb=new N({name:"__TypeKind",description:"An enum describing what kind of type a given `__Type` is.",values:{SCALAR:{value:X.SCALAR,description:"Indicates this type is a scalar."},OBJECT:{value:X.OBJECT,description:"Indicates this type is an object. `fields` and `interfaces` are valid fields."},INTERFACE:{value:X.INTERFACE,description:"Indicates this type is an interface. `fields`, `interfaces`, and `possibleTypes` are valid fields."},UNION:{value:X.UNION,description:"Indicates this type is a union. `possibleTypes` is a valid field."},
ENUM:{value:X.ENUM,description:"Indicates this type is an enum. `enumValues` is a valid field."},INPUT_OBJECT:{value:X.INPUT_OBJECT,description:"Indicates this type is an input object. `inputFields` is a valid field."},LIST:{value:X.LIST,description:"Indicates this type is a list. `ofType` is a valid field."},NON_NULL:{value:X.NON_NULL,description:"Indicates this type is a non-null. `ofType` is a valid field."}}});new Q(ob);Object.create(null);new Q(T);Object.create(null);Object.create(null);new Q(T);
Object.create(null);Object.freeze([ob,nb,pb,W,sb,qb,tb,rb]);
class ub{constructor(a){var b,c;this.__validationErrors=!0===a.assumeValid?[]:void 0;k(a)||g(!1,"Must provide configuration object.");!a.types||Array.isArray(a.types)||g(!1,`"types" must be Array if provided but got: ${t(a.types)}.`);!a.directives||Array.isArray(a.directives)||g(!1,'"directives" must be Array if provided but got: '+`${t(a.directives)}.`);this.description=a.description;this.extensions=A(a.extensions);this.astNode=a.astNode;this.extensionASTNodes=null!==(b=a.extensionASTNodes)&&void 0!==
b?b:[];this._queryType=a.query;this._mutationType=a.mutation;this._subscriptionType=a.subscription;this._directives=null!==(c=a.directives)&&void 0!==c?c:kb;b=new Set(a.types);if(null!=a.types)for(let d of a.types)b.delete(d),Z(d,b);null!=this._queryType&&Z(this._queryType,b);null!=this._mutationType&&Z(this._mutationType,b);null!=this._subscriptionType&&Z(this._subscriptionType,b);for(let d of this._directives)if(u(d,fb))for(let e of d.args)Z(e.type,b);Z(ob,b);this._typeMap=Object.create(null);this._subTypeMap=
Object.create(null);this._implementationsMap=Object.create(null);for(let d of b)if(null!=d){(a=d.name)||g(!1,"One of the provided types for building the Schema is missing a name.");if(void 0!==this._typeMap[a])throw Error(`Schema must contain uniquely named types but contains multiple types named "${a}".`);this._typeMap[a]=d;if(u(d,L))for(let e of d.getInterfaces())u(e,L)&&(a=this._implementationsMap[e.name],void 0===a&&(a=this._implementationsMap[e.name]={objects:[],interfaces:[]}),a.interfaces.push(d));
else if(u(d,K))for(let e of d.getInterfaces())u(e,L)&&(a=this._implementationsMap[e.name],void 0===a&&(a=this._implementationsMap[e.name]={objects:[],interfaces:[]}),a.objects.push(d))}}get [Symbol.toStringTag](){return"GraphQLSchema"}getQueryType(){return this._queryType}getMutationType(){return this._mutationType}getSubscriptionType(){return this._subscriptionType}getRootType(a){switch(a){case m.QUERY:return this.getQueryType();case m.MUTATION:return this.getMutationType();case m.SUBSCRIPTION:return this.getSubscriptionType()}}getTypeMap(){return this._typeMap}getType(a){return this.getTypeMap()[a]}getPossibleTypes(a){return u(a,
M)?a.getTypes():this.getImplementations(a).objects}getImplementations(a){a=this._implementationsMap[a.name];return null!==a&&void 0!==a?a:{objects:[],interfaces:[]}}isSubType(a,b){let c=this._subTypeMap[a.name];if(void 0===c){c=Object.create(null);if(u(a,M))for(var d of a.getTypes())c[d.name]=!0;else{d=this.getImplementations(a);for(let e of d.objects)c[e.name]=!0;for(let e of d.interfaces)c[e.name]=!0}this._subTypeMap[a.name]=c}return void 0!==c[b.name]}getDirectives(){return this._directives}getDirective(a){return this.getDirectives().find(b=>
b.name===a)}toConfig(){return{description:this.description,query:this.getQueryType(),mutation:this.getMutationType(),subscription:this.getSubscriptionType(),types:Object.values(this.getTypeMap()),directives:this.getDirectives(),extensions:this.extensions,astNode:this.astNode,extensionASTNodes:this.extensionASTNodes,assumeValid:void 0!==this.__validationErrors}}}
function Z(a,b){if(a)for(;Ra(a);)a=a.ofType;else a=void 0;if(!b.has(a))if(b.add(a),u(a,M))for(let c of a.getTypes())Z(c,b);else if(u(a,K)||u(a,L)){for(let c of a.getInterfaces())Z(c,b);for(let c of Object.values(a.getFields())){Z(c.type,b);for(let d of c.args)Z(d.type,b)}}else if(u(a,O))for(let c of Object.values(a.getFields()))Z(c.type,b);return b}var vb=ub({query:"queryType"});export function init(){Graphql.createGraphqlRouter({schema:vb,graphiql:!0})}
